'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PDFViewer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMBack&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 465.625,314.353L 262.756,516.907C 251.645,528.019 240.373,539.288 240.215,561.512L 240.215,561.512C 240.056,582.308 248.945,593.26 262.756,607.069L 465.625,809.941C 47 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMBack() As String
            Get
                Return ResourceManager.GetString("CCMBack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMEnd&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 223.385,336.895L 223.385,787.4C 223.385,809.941 245.927,832.481 268.468,832.481L 268.468,832.481C 291.009,832.481 302.28,821.211 313.551,809.941L 501.181,622.152L 501.1 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMEnd() As String
            Get
                Return ResourceManager.GetString("CCMEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMForward&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 240.212,336.895L 240.212,787.4C 240.212,809.941 262.753,832.481 285.295,832.481L 285.295,832.481C 307.836,832.481 319.107,821.211 330.377,809.941L 533.248,607.069C  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMForward() As String
            Get
                Return ResourceManager.GetString("CCMForward", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMPDF&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 194.238,936.191L 752.074,936.191L 749.954,414.977C 749.262,348.299 592.17,233.308 512.606,189.164L 194.238,188.105L 194.238,936.191 Z &quot;&gt;
        '''						&lt;GeometryDrawing.Brush&gt;        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMPDF() As String
            Get
                Return ResourceManager.GetString("CCMPDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;_449000765__print&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FF3C3C3F&quot; Geometry=&quot;F1 M 160.451,428.188L 731.916,428.188C 739.853,428.188 747.791,436.124 747.791,444.063L 747.791,825.039L 144.577,825.039L 144.577,444.063C 144.5 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMPrint() As String
            Get
                Return ResourceManager.GetString("CCMPrint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMPrintSelect&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FF434242&quot; Geometry=&quot;F1 M 176.068,380.396L 687.578,380.396C 694.682,380.396 701.788,387.5 701.788,394.604L 701.788,735.612L 161.86,735.612L 161.86,394.604C 161.86,387.5 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMPrintSelect() As String
            Get
                Return ResourceManager.GetString("CCMPrintSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMStart&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 482.449,314.353L 294.82,501.667L 294.82,300.225C 294.82,295.781 291.168,292.289 286.881,292.289L 231.323,292.289C 226.877,292.289 223.385,295.781 223.385,300.225L 223 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMStart() As String
            Get
                Return ResourceManager.GetString("CCMStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMZoom100&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 372.601,592.307L 428.16,536.749L 480.545,589.133L 424.985,644.693L 372.601,592.307 Z &quot;&gt;
        '''						&lt;GeometryDrawing.Brush&gt;
        '''							&lt;LinearGradientBrush StartPoint=&quot;0.20 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMZoom100() As String
            Get
                Return ResourceManager.GetString("CCMZoom100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;_449000748__zoom_in&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 372.601,592.307L 428.16,536.749L 480.545,589.133L 424.985,644.693L 372.601,592.307 Z &quot;&gt;
        '''						&lt;GeometryDrawing.Brush&gt;
        '''							&lt;LinearGradientBrush StartPo [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMZoomIn() As String
            Get
                Return ResourceManager.GetString("CCMZoomIn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;_449000756__zoom_out&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 372.601,592.307L 428.16,536.749L 480.545,589.133L 424.985,644.693L 372.601,592.307 Z &quot;&gt;
        '''						&lt;GeometryDrawing.Brush&gt;
        '''							&lt;LinearGradientBrush StartP [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMZoomOut() As String
            Get
                Return ResourceManager.GetString("CCMZoomOut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMZoomPage&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 381.935,602.973L 437.493,547.416L 489.879,599.8L 434.319,655.36L 381.935,602.973 Z &quot;&gt;
        '''						&lt;GeometryDrawing.Brush&gt;
        '''							&lt;LinearGradientBrush StartPoint=&quot;0.205 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMZoomPage() As String
            Get
                Return ResourceManager.GetString("CCMZoomPage", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
