'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CCM.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMAlignmentBQuadrant&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 280.651,264.735L 439.391,264.735C 448.915,264.735 455.265,271.085 455.265,280.609L 455.265,439.349C 455.265,448.873 448.915,455.224 439.391,455.224L 280. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMAlignmentB() As String
            Get
                Return ResourceManager.GetString("CCMAlignmentB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMAlignmentCQuadrant&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FF279DFF&quot; Geometry=&quot;F1 M 280.651,264.735L 439.391,264.735C 448.915,264.735 455.265,271.085 455.265,280.609L 455.265,439.349C 455.265,448.873 448.915,455.224 439 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMAlignmentC() As String
            Get
                Return ResourceManager.GetString("CCMAlignmentC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMAlignmentLQuadrant&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 280.651,264.735L 439.391,264.735C 448.915,264.735 455.265,271.085 455.265,280.609L 455.265,439.349C 455.265,448.873 448.915,455.224 439.391,455.224L 280. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMAlignmentL() As String
            Get
                Return ResourceManager.GetString("CCMAlignmentL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMAlignmentLLQuadrant&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 280.651,264.735L 439.391,264.735C 448.915,264.735 455.265,271.085 455.265,280.609L 455.265,439.349C 455.265,448.873 448.915,455.224 439.391,455.224L 280 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMAlignmentLL() As String
            Get
                Return ResourceManager.GetString("CCMAlignmentLL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMAlignmentLRQuadrant&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 280.651,264.735L 439.391,264.735C 448.915,264.735 455.265,271.085 455.265,280.609L 455.265,439.349C 455.265,448.873 448.915,455.224 439.391,455.224L 280 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMAlignmentLR() As String
            Get
                Return ResourceManager.GetString("CCMAlignmentLR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMAlignmentRQuadrant&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 280.651,264.735L 439.391,264.735C 448.915,264.735 455.265,271.085 455.265,280.609L 455.265,439.349C 455.265,448.873 448.915,455.224 439.391,455.224L 280. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMAlignmentR() As String
            Get
                Return ResourceManager.GetString("CCMAlignmentR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMAlignmentTQuadrant&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 280.651,264.735L 439.391,264.735C 448.915,264.735 455.265,271.085 455.265,280.609L 455.265,439.349C 455.265,448.873 448.915,455.224 439.391,455.224L 280. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMAlignmentT() As String
            Get
                Return ResourceManager.GetString("CCMAlignmentT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMAlignmentULQuadrant&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 280.651,264.735L 439.391,264.735C 448.915,264.735 455.265,271.085 455.265,280.609L 455.265,439.349C 455.265,448.873 448.915,455.224 439.391,455.224L 280 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMAlignmentUL() As String
            Get
                Return ResourceManager.GetString("CCMAlignmentUL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMAlignmentURQuadrant&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 280.651,264.735L 439.391,264.735C 448.915,264.735 455.265,271.085 455.265,280.609L 455.265,439.349C 455.265,448.873 448.915,455.224 439.391,455.224L 280 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMAlignmentUR() As String
            Get
                Return ResourceManager.GetString("CCMAlignmentUR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMBack&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 465.625,314.353L 262.756,516.907C 251.645,528.019 240.373,539.288 240.215,561.512L 240.215,561.512C 240.056,582.308 248.945,593.26 262.756,607.069L 465.625,809.941C 47 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMBack() As String
            Get
                Return ResourceManager.GetString("CCMBack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMBackground&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 159.891,292.289C 142.356,292.289 128.143,306.503 128.143,324.037L 128.143,800.257C 128.143,817.792 142.356,832.005 159.891,832.005L 636.111,832.005C 653.645,832. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMBackground() As String
            Get
                Return ResourceManager.GetString("CCMBackground", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CCMBlock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CCMBlock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CCMBody() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CCMBody", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMBorder&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;DrawingGroup ClipGeometry=&quot;F1 M 0,1122.67L 793.701,1122.67L 793.701,0.146606L 0,0.146606L 0,1122.67 Z &quot;&gt;
        '''						&lt;DrawingGroup.Children&gt;
        '''							&lt;GeometryDrawing Geometry=&quot;F1 M 56.7089,363.721L 56. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMBorder() As String
            Get
                Return ResourceManager.GetString("CCMBorder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMCheck&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 499.212,450.921L 364.811,585.321L 297.083,518.651C 292.849,514.417 286.499,514.417 282.267,518.651L 230.411,570.507C 226.177,574.739 226.177,581.089 230.411,585.321L  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMCheck() As String
            Get
                Return ResourceManager.GetString("CCMCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMCheckEmpty&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 398.676,64.8734C 582.783,64.8734 732.032,164.372 732.032,287.111C 732.032,409.848 582.783,509.347 398.676,509.347C 214.569,509.347 65.32,409.848 65.32,287.111C 6 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMCheckEmpty() As String
            Get
                Return ResourceManager.GetString("CCMCheckEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMCheckMark&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FF000000&quot; Geometry=&quot;F1 M 53.0454,373.177L 237.259,586.955C 331.119,395.631 446.017,219.619 630.7,52.512C 492.481,130.505 340.117,278.609 209.967,461.872L 53.0454,373.177 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMCheckMark() As String
            Get
                Return ResourceManager.GetString("CCMCheckMark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMClipboard&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 151.953,276.479C 139.255,276.479 128.143,287.591 128.143,300.288L 128.143,879.691C 128.143,892.389 139.255,903.501 151.953,903.501L 644.047,903.501C 656.745,903.5 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMClipboard() As String
            Get
                Return ResourceManager.GetString("CCMClipboard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMCritical&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 53.3339,562.147C 53.3339,755.017 209.693,911.376 402.562,911.376L 402.562,911.376C 595.431,911.376 751.79,755.017 751.79,562.147L 751.79,562.147C 751.79,369.277 59 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMCritical() As String
            Get
                Return ResourceManager.GetString("CCMCritical", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMCross&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 174.929,314.512C 40.0001,451.029 40.0001,673.265 174.929,809.783L 174.929,809.783C 311.445,944.712 533.683,944.712 670.2,809.783L 670.2,809.783C 805.128,673.265 805.1 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMCross() As String
            Get
                Return ResourceManager.GetString("CCMCross", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CCMDivider() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CCMDivider", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMDown&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 560.708,397.057L 398,559.765L 235.291,397.057C 219.736,381.66 194.496,381.66 179.097,397.057L 128.619,447.537C 116.237,459.917 116.237,480.079 128.619,492.459L 358.792 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMDown() As String
            Get
                Return ResourceManager.GetString("CCMDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CCMField() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CCMField", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMFontBold&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 274.303,371.565L 274.303,623.963C 274.303,642.536 278.907,656.821 288.272,666.188C 297.637,675.712 311.448,680.633 330.021,680.633C 357.324,680.633 382.247,674.441 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMFontBold() As String
            Get
                Return ResourceManager.GetString("CCMFontBold", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMFontItalic&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 321.645,212.919L 315.931,230.857C 352.283,233.237 375.3,238 384.824,245.461L 384.824,245.461C 394.508,252.763 399.271,262.764 399.271,275.621L 399.271,275.621C 3 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMFontItalic() As String
            Get
                Return ResourceManager.GetString("CCMFontItalic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMFontUnderline&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 431.547,671.704L 348.406,476.084L 263.291,671.704L 431.547,671.704 Z M 444.834,702.882L 249.608,702.882L 225.403,758.923C 217.642,777.603 213.826,793.259 213. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMFontUnderline() As String
            Get
                Return ResourceManager.GetString("CCMFontUnderline", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CCMFooter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CCMFooter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CCMFormHeader() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CCMFormHeader", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMForward&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 240.212,336.895L 240.212,787.4C 240.212,809.941 262.753,832.481 285.295,832.481L 285.295,832.481C 307.836,832.481 319.107,821.211 330.377,809.941L 533.248,607.069C  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMForward() As String
            Get
                Return ResourceManager.GetString("CCMForward", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CCMGroup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CCMGroup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMHandwriting&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FF008BFF&quot; Geometry=&quot;F1 M 9.40934,5.55465C 10.5933,4.93062 11.552,4.13196 11.552,3.41195C 11.552,3.07597 11.4093,2.88395 11.0733,2.89994C 10.4653,2.93197 9.76133,3.7159 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMHandwriting() As String
            Get
                Return ResourceManager.GetString("CCMHandwriting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CCMHeader() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CCMHeader", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMImage&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 88.4573,324.037C 70.924,324.037 56.708,338.252 56.708,355.785L 56.708,768.509C 56.708,786.043 70.924,800.257 88.4573,800.257L 707.543,800.257C 725.077,800.257 739.291 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMImage() As String
            Get
                Return ResourceManager.GetString("CCMImage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMImageBlue&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FFFFFFFF&quot; Geometry=&quot;F1 M 88.4571,324.036L 707.542,324.036C 725.077,324.036 739.292,338.251 739.292,355.786L 739.292,768.508C 739.292,786.043 725.077,800.258 707.542,800. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMImageBlue() As String
            Get
                Return ResourceManager.GetString("CCMImageBlue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMImageSample&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 515.937,93.2987C 496.625,109.633 466.008,122.388 464.809,122.223L 464.809,122.223C 463.615,122.057 576.504,138.16 576.504,138.16L 576.504,138.16C 576.504,138.16 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMImageSample() As String
            Get
                Return ResourceManager.GetString("CCMImageSample", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMJustificationCenter&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 223.385,260.54C 214.619,260.54 207.511,267.648 207.511,276.414L 207.511,324.037C 207.511,332.804 214.619,339.911 223.385,339.911L 572.615,339.911C 581.3 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMJustificationCenter() As String
            Get
                Return ResourceManager.GetString("CCMJustificationCenter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMJustificationJustify&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 80.5199,609.769C 71.7533,609.769 64.6466,616.876 64.6466,625.644L 64.6466,673.265C 64.6466,682.033 71.7533,689.139 80.5199,689.139L 715.481,689.139C 72 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMJustificationJustify() As String
            Get
                Return ResourceManager.GetString("CCMJustificationJustify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMJustificationLeft&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 80.5199,260.54C 71.7533,260.54 64.6466,267.648 64.6466,276.414L 64.6466,324.037C 64.6466,332.804 71.7533,339.911 80.5199,339.911L 429.749,339.911C 438.516 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMJustificationLeft() As String
            Get
                Return ResourceManager.GetString("CCMJustificationLeft", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMJustificationRight&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 366.251,260.54C 357.485,260.54 350.377,267.648 350.377,276.414L 350.377,324.037C 350.377,332.804 357.485,339.911 366.251,339.911L 715.481,339.911C 724.24 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMJustificationRight() As String
            Get
                Return ResourceManager.GetString("CCMJustificationRight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMLock&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FF434242&quot; Geometry=&quot;F1 M 207.512,548.876L 269.421,548.876L 269.421,386.961C 269.421,315.528 326.568,256.794 398,256.794C 469.433,256.794 526.58,315.528 526.58,386.961L 526.58 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMLock() As String
            Get
                Return ResourceManager.GetString("CCMLock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMLoremIpsum&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FF000000&quot; Geometry=&quot;F1 M 42.0466,3.94775C 43.7347,3.69706 46.7027,4.27576 50.9533,5.68241L 51.7973,6.38509C 52.0773,6.63574 52.5307,6.85441 53.156,7.04109L 52.8747,7.60 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMLoremIpsum() As String
            Get
                Return ResourceManager.GetString("CCMLoremIpsum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CCMMCQ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CCMMCQ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CCMMCQData() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CCMMCQData", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMMCQLoad&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 134.808,839.88C 134.808,863.689 142.747,887.501 174.493,887.501L 626.904,887.501C 642.777,887.501 658.651,871.628 658.651,855.755L 658.651,316.036L 174.493,316.036C [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMMCQLoad() As String
            Get
                Return ResourceManager.GetString("CCMMCQLoad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMMinus&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 48.772,562.147C 48.772,755.809 204.337,911.376 398,911.376L 398,911.376C 591.663,911.376 747.228,755.809 747.228,562.147L 747.228,562.147C 747.228,368.485 591.663,212 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMMinus() As String
            Get
                Return ResourceManager.GetString("CCMMinus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMNotVisible&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 64.6467,562.147C 128.143,673.265 255.135,736.763 398,736.763L 398,736.763C 540.867,736.763 667.857,673.265 731.355,562.147L 731.355,562.147C 667.857,451.029 540. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMNotVisible() As String
            Get
                Return ResourceManager.GetString("CCMNotVisible", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMNumbering&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 26.6667,26.6253L 121.911,26.6253L 121.911,121.869L 26.6667,121.869L 26.6667,26.6253 Z &quot;&gt;
        '''						&lt;GeometryDrawing.Pen&gt;
        '''							&lt;Pen Thickness=&quot;13.3333&quot; MiterLimit= [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMNumbering() As String
            Get
                Return ResourceManager.GetString("CCMNumbering", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMOne&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 53.3336,561.408C 53.3336,754.277 209.692,910.633 402.562,910.633L 402.562,910.633C 595.431,910.633 751.79,754.277 751.79,561.408L 751.79,561.408C 751.79,368.537 595.431 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMOne() As String
            Get
                Return ResourceManager.GetString("CCMOne", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CCMPageBreak() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CCMPageBreak", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CCMPageHeader() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CCMPageHeader", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CCMPDF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CCMPDF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMPDF&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 194.238,936.191L 752.074,936.191L 749.954,414.977C 749.262,348.299 592.17,233.308 512.606,189.164L 194.238,188.105L 194.238,936.191 Z &quot;&gt;
        '''						&lt;GeometryDrawing.Brush&gt;        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMPDF1() As String
            Get
                Return ResourceManager.GetString("CCMPDF1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMPencil&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FFEBEBEB&quot; Geometry=&quot;F1 M 135.825,668.503L 292.978,825.656L 56.4543,903.439L 135.825,668.503 Z &quot;/&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FF0078C8&quot; Geometry=&quot;F1 M 574.835,438.642L 6 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMPencil() As String
            Get
                Return ResourceManager.GetString("CCMPencil", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMPlus&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 48.772,562.147C 48.772,755.809 204.337,911.376 398,911.376L 398,911.376C 591.663,911.376 747.228,755.809 747.228,562.147L 747.228,562.147C 747.228,368.485 591.663,212. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMPlus() As String
            Get
                Return ResourceManager.GetString("CCMPlus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CCMProperties() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CCMProperties", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;Layer_1&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 367.551,253.504L 367.551,304.3C 189.763,313.825 48.4826,413.832 48.4826,536.061L 48.4826,536.061C 48.4826,634.48 140.552,718.613 269.131,751.948L 289.768,686.865C 186. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMReplacePDF() As String
            Get
                Return ResourceManager.GetString("CCMReplacePDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;_449000760__save&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 136.64,263.099L 716.041,263.099L 795.412,342.468L 795.412,921.869C 795.412,942.507 777.951,961.556 755.727,961.556L 136.64,961.556C 114.417,961.556 96.955,942 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMSave() As String
            Get
                Return ResourceManager.GetString("CCMSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CCMSection() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CCMSection", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMSelection&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 480.228,305.305C 464.355,305.305 448.48,321.18 448.48,337.053L 448.48,337.053C 448.48,344.991 448.48,352.927 464.355,368.803L 482.925,387.373L 398,472.299L 313.07 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMSelection() As String
            Get
                Return ResourceManager.GetString("CCMSelection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMStretchFill&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 480.228,305.305C 464.355,305.305 448.48,321.18 448.48,337.053L 448.48,337.053C 448.48,344.991 448.48,352.927 464.355,368.803L 482.925,387.373L 398,472.299L 313. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMStretchFill() As String
            Get
                Return ResourceManager.GetString("CCMStretchFill", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMAlignmentStretchBoth&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 377.364,220.856L 275.769,322.449C 264.657,333.561 264.657,355.785 275.769,366.897L 275.769,366.897C 282.12,373.247 286.881,378.008 310.693,378.008L 334 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMStretchUniform() As String
            Get
                Return ResourceManager.GetString("CCMStretchUniform", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMSubject&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 259.896,366.897C 259.896,443.169 321.727,505 398,505L 398,505C 474.273,505 536.104,443.169 536.104,366.897L 536.104,366.897C 536.104,290.624 474.273,228.793 398,228 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMSubject() As String
            Get
                Return ResourceManager.GetString("CCMSubject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CCMSubjects() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CCMSubjects", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CCMSubSection() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CCMSubSection", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMTag&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 163.064,251.016C 155.128,251.016 148.779,258.953 148.779,266.891L 148.779,493.889C 148.779,498.651 150.365,501.825 151.953,505L 490.069,843.117C 496.42,847.879 505.944, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMTag() As String
            Get
                Return ResourceManager.GetString("CCMTag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMStaticText&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 562.257,7.13733L 562.257,173.815L 546.384,173.815C 536.859,135.717 525.747,107.143 514.635,91.2693C 501.936,73.808 486.063,61.1094 465.425,51.584C 454.313,45.233 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMText() As String
            Get
                Return ResourceManager.GetString("CCMText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMTrashValid&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;DrawingGroup ClipGeometry=&quot;F1 M -8.13802e-005,0.146484L 793.701,0.146484L 793.701,1122.67L -8.13802e-005,1122.67L -8.13802e-005,0.146484 Z &quot;&gt;
        '''						&lt;DrawingGroup.Children&gt;
        '''							&lt;GeometryDr [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMTrashValid() As String
            Get
                Return ResourceManager.GetString("CCMTrashValid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMUp&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 358.792,401.66L 128.619,631.835C 116.237,644.216 116.237,664.376 128.619,676.757L 179.097,727.237C 194.496,742.635 219.736,742.635 235.291,727.237L 398,564.529L 560.708, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMUp() As String
            Get
                Return ResourceManager.GetString("CCMUp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMVisible&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FFFFFFFF&quot; Geometry=&quot;F1 M 731.354,562.147C 667.858,451.028 540.866,387.533 397.999,387.533C 255.134,387.533 128.142,451.028 64.6461,562.147C 128.142,673.266 255.134,736.762 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMVisible() As String
            Get
                Return ResourceManager.GetString("CCMVisible", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconCCM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconCCM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property IconCCM1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("IconCCM1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property IconHelp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("IconHelp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TextureCardboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextureCardboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TextureVintage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextureVintage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
