'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Survey.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMCross&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 174.929,314.512C 40.0001,451.029 40.0001,673.265 174.929,809.783L 174.929,809.783C 311.445,944.712 533.683,944.712 670.2,809.783L 670.2,809.783C 805.128,673.265 805.1 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMCross() As String
            Get
                Return ResourceManager.GetString("CCMCross", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMDown&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 560.708,397.057L 398,559.765L 235.291,397.057C 219.736,381.66 194.496,381.66 179.097,397.057L 128.619,447.537C 116.237,459.917 116.237,480.079 128.619,492.459L 358.792 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMDown() As String
            Get
                Return ResourceManager.GetString("CCMDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMQuestionMark&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 48.772,562.147C 48.772,755.809 204.337,911.376 398,911.376L 398,911.376C 591.663,911.376 747.228,755.809 747.228,562.147L 747.228,562.147C 747.228,368.485 591. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMQuestionMark() As String
            Get
                Return ResourceManager.GetString("CCMQuestionMark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;_449000760__save&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 136.64,263.099L 716.041,263.099L 795.412,342.468L 795.412,921.869C 795.412,942.507 777.951,961.556 755.727,961.556L 136.64,961.556C 114.417,961.556 96.955,942 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMSave() As String
            Get
                Return ResourceManager.GetString("CCMSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMTick&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 174.929,314.512C 40.0001,451.029 40.0001,673.265 174.929,809.783L 174.929,809.783C 311.445,944.712 533.683,944.712 670.2,809.783L 670.2,809.783C 805.128,673.265 805.12 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMTick() As String
            Get
                Return ResourceManager.GetString("CCMTick", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMUp&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 358.792,401.66L 128.619,631.835C 116.237,644.216 116.237,664.376 128.619,676.757L 179.097,727.237C 194.496,742.635 219.736,742.635 235.291,727.237L 398,564.529L 560.708, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMUp() As String
            Get
                Return ResourceManager.GetString("CCMUp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;GNU&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;DrawingGroup ClipGeometry=&quot;F1 M -8.13802e-005,1122.67L 793.701,1122.67L 793.701,0.146484L -8.13802e-005,0.146484L -8.13802e-005,1122.67 Z &quot;&gt;
        '''						&lt;DrawingGroup.Children&gt;
        '''							&lt;GeometryDrawing Geome [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property GNU() As String
            Get
                Return ResourceManager.GetString("GNU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\deff0{\fonttbl{\f0 \fswiss Helvetica;}{\f1 Courier;}}
        '''{\colortbl;\red255\green0\blue0;\red0\green0\blue255;}
        '''\widowctrl\hyphauto
        '''
        '''{\pard \ql \f0 \sa180 \li0 \fi0 \b \fs28 GNU GENERAL PUBLIC LICENSE\par}
        '''{\pard \ql \f0 \sa180 \li0 \fi0 Version 3, 29 June 2007\par}
        '''{\pard \ql \f0 \sa180 \li0 \fi0 Copyright \u169? 2007 Free Software Foundation, Inc. &lt;{\field{\*\fldinst{HYPERLINK &quot;http://fsf.org/&quot;}}{\fldrslt{\ul
        '''http://fsf.org/
        '''}}}
        '''&gt;\par}
        '''{\pard \ql \f0 \sa180 \li0 \fi0 Everyone is permitted to copy [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property gpl() As String
            Get
                Return ResourceManager.GetString("gpl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconCCM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconCCM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconConfiguration() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconConfiguration", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property IconConfiguration1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("IconConfiguration1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconExit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconExit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property IconHelp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("IconHelp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property IconInfo() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("IconInfo", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconScanner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconScanner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property IconSurvey() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("IconSurvey", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;CCM.FormMain z:Id=&quot;i1&quot; xmlns=&quot;http://schemas.datacontract.org/2004/07/CCM&quot; xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:z=&quot;http://schemas.microsoft.com/2003/10/Serialization/&quot;&gt;&lt;m_DataObject i:type=&quot;CCM.BaseFormItem.DataObjectClass&quot;&gt;&lt;ChildrenSave xmlns:a=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;&lt;a:KeyValueOfguidstring&gt;&lt;a:Key&gt;a36c9455-29bd-433f-aa5b-d73cb9b4d705&lt;/a:Key&gt;&lt;a:Value&gt;CCM.CCM+FormProperties, CCM, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null&lt;/a:Value&gt;&lt;/a:KeyV [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Survey_v2_Help_File() As String
            Get
                Return ResourceManager.GetString("Survey_v2_Help_File", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TextureCardboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextureCardboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TextureVintage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextureVintage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
