'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Common.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMCheckboxChecked&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FFFFFFFF&quot; Geometry=&quot;F1 M 116.829,212.919L 688.293,212.919C 723.363,212.919 751.789,241.346 751.789,276.414L 751.789,847.879C 751.789,882.947 723.363,911.375 688.29 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMCheckboxChecked() As String
            Get
                Return ResourceManager.GetString("CCMCheckboxChecked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMCheckboxUnchecked&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FFFFFFFF&quot; Geometry=&quot;F1 M 116.829,53.5439L 688.293,53.5439C 723.363,53.5439 751.789,81.9707 751.789,117.039L 751.789,688.504C 751.789,723.572 723.363,752 688.293, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMCheckboxUnchecked() As String
            Get
                Return ResourceManager.GetString("CCMCheckboxUnchecked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMCheckEmpty&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 398.676,64.8734C 582.783,64.8734 732.032,164.372 732.032,287.111C 732.032,409.848 582.783,509.347 398.676,509.347C 214.569,509.347 65.32,409.848 65.32,287.111C 6 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMCheckEmpty() As String
            Get
                Return ResourceManager.GetString("CCMCheckEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMCheckEmptyBlack&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 398.676,64.8734C 582.783,64.8734 732.032,164.372 732.032,287.111C 732.032,409.848 582.783,509.347 398.676,509.347C 214.569,509.347 65.32,409.848 65.32,287.1 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMCheckEmptyBlack() As String
            Get
                Return ResourceManager.GetString("CCMCheckEmptyBlack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMCheckFilled&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FF434242&quot; Geometry=&quot;F1 M 398.676,64.8734C 582.783,64.8734 732.032,164.372 732.032,287.111C 732.032,409.848 582.783,509.347 398.676,509.347C 214.569,509.347 65.32,409.8 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMCheckFilled() As String
            Get
                Return ResourceManager.GetString("CCMCheckFilled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMCheckInner&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FF000000&quot; Geometry=&quot;F1 M 398.676,64.8734C 582.783,64.8734 732.032,164.372 732.032,287.111C 732.032,409.848 582.783,509.347 398.676,509.347C 214.569,509.347 65.32,409.84 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMCheckInner() As String
            Get
                Return ResourceManager.GetString("CCMCheckInner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconBack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconBack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconEject() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconEject", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconEjectInverted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconEjectInverted", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconFirst() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconFirst", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconForward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconForward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconGray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconGray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconLast() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconLast", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconYellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconYellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TextureCardboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextureCardboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TextureCardboardDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextureCardboardDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TextureCardboardMedium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextureCardboardMedium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
