'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Scanner.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMBack&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 465.625,314.353L 262.756,516.907C 251.645,528.019 240.373,539.288 240.215,561.512L 240.215,561.512C 240.056,582.308 248.945,593.26 262.756,607.069L 465.625,809.941C 47 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMBack() As String
            Get
                Return ResourceManager.GetString("CCMBack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMBackPink&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 465.625,314.353L 262.756,516.907C 251.645,528.019 240.373,539.288 240.215,561.512L 240.215,561.512C 240.056,582.308 248.945,593.26 262.756,607.069L 465.625,809.941 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMBackPink() As String
            Get
                Return ResourceManager.GetString("CCMBackPink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMCheckMark&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FF000000&quot; Geometry=&quot;F1 M 53.0454,373.177L 237.259,586.955C 331.119,395.631 446.017,219.619 630.7,52.512C 492.481,130.505 340.117,278.609 209.967,461.872L 53.0454,373.177 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMCheckMark() As String
            Get
                Return ResourceManager.GetString("CCMCheckMark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMDefinitions&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 151.953,276.479C 139.255,276.479 128.143,287.591 128.143,300.288L 128.143,879.691C 128.143,892.389 139.255,903.501 151.953,903.501L 644.047,903.501C 656.745,903 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMDefinitions() As String
            Get
                Return ResourceManager.GetString("CCMDefinitions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMDoubleGears&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 253.292,444.425C 245.356,444.425 239.007,450.775 237.419,460.299L 232.656,503.16C 232.656,509.509 227.895,514.271 223.132,515.857L 223.132,515.857C 212.02,519.0 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMDoubleGears() As String
            Get
                Return ResourceManager.GetString("CCMDoubleGears", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMFilter&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 112.267,276.414L 112.267,325.783L 334.504,546.273C 342.44,554.209 350.379,562.147 350.379,578.656L 350.379,879.627L 445.623,911.376L 445.623,578.02C 445.623,562.147  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMFilter() As String
            Get
                Return ResourceManager.GetString("CCMFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMFilterGreen&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FF8CC63F&quot; Geometry=&quot;F1 M 350.378,879.628L 445.622,911.375L 445.622,578.021C 445.622,562.148 453.558,554.21 461.496,546.273L 683.732,324.037L 683.732,276.414L 112.268,2 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMFilterGreen() As String
            Get
                Return ResourceManager.GetString("CCMFilterGreen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMFilterOrange&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FFF7931E&quot; Geometry=&quot;F1 M 350.378,879.628L 445.622,911.375L 445.622,578.021C 445.622,562.148 453.558,554.21 461.496,546.273L 683.732,324.037L 683.732,276.414L 112.268, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMFilterOrange() As String
            Get
                Return ResourceManager.GetString("CCMFilterOrange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMForward&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 240.212,336.895L 240.212,787.4C 240.212,809.941 262.753,832.481 285.295,832.481L 285.295,832.481C 307.836,832.481 319.107,821.211 330.377,809.941L 533.248,607.069C  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMForward() As String
            Get
                Return ResourceManager.GetString("CCMForward", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMForwardPink&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 240.212,336.895L 240.212,787.4C 240.212,809.941 262.753,832.481 285.295,832.481L 285.295,832.481C 307.836,832.481 319.107,821.211 330.377,809.941L 533.248,607.0 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMForwardPink() As String
            Get
                Return ResourceManager.GetString("CCMForwardPink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMMark0&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FFFFFFFF&quot; Geometry=&quot;F1 M 424.147,106.373C 599.487,106.373 741.627,248.513 741.627,423.853C 741.627,599.193 599.487,741.333 424.147,741.333C 248.808,741.333 106.667,599.193 1 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMMark0() As String
            Get
                Return ResourceManager.GetString("CCMMark0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMMark1&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FFFFFFFF&quot; Geometry=&quot;F1 M 424.147,106.373C 599.487,106.373 741.627,248.513 741.627,423.853C 741.627,599.192 599.487,741.333 424.147,741.333C 248.808,741.333 106.667,599.192 1 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMMark1() As String
            Get
                Return ResourceManager.GetString("CCMMark1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMMark2&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FFFFFFFF&quot; Geometry=&quot;F1 M 424.147,106.373C 599.487,106.373 741.627,248.513 741.627,423.853C 741.627,599.192 599.487,741.333 424.147,741.333C 248.808,741.333 106.667,599.192 1 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMMark2() As String
            Get
                Return ResourceManager.GetString("CCMMark2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMNotVisible&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 64.6467,562.147C 128.143,673.265 255.135,736.763 398,736.763L 398,736.763C 540.867,736.763 667.857,673.265 731.355,562.147L 731.355,562.147C 667.857,451.029 540. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMNotVisible() As String
            Get
                Return ResourceManager.GetString("CCMNotVisible", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMPDF&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 194.238,936.191L 752.074,936.191L 749.954,414.977C 749.262,348.299 592.17,233.308 512.606,189.164L 194.238,188.105L 194.238,936.191 Z &quot;&gt;
        '''						&lt;GeometryDrawing.Brush&gt;        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMPDF() As String
            Get
                Return ResourceManager.GetString("CCMPDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;_449000760__save&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 136.64,263.099L 716.041,263.099L 795.412,342.468L 795.412,921.869C 795.412,942.507 777.951,961.556 755.727,961.556L 136.64,961.556C 114.417,961.556 96.955,942 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMSave() As String
            Get
                Return ResourceManager.GetString("CCMSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMScan&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FF434242&quot; Geometry=&quot;F1 M 136.079,317.243L 231.323,317.243C 235.609,317.243 239.26,320.894 239.26,325.181L 239.26,333.118L 255.135,333.118L 255.135,364.866L 112.268,364.866L 1 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMScan() As String
            Get
                Return ResourceManager.GetString("CCMScan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMScanSelect&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FF434242&quot; Geometry=&quot;F1 M 157.744,317.243L 252.988,317.243C 257.275,317.243 260.926,320.894 260.926,325.181L 260.926,333.118L 276.8,333.118L 276.8,364.866L 133.934,364.8 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMScanSelect() As String
            Get
                Return ResourceManager.GetString("CCMScanSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMVisible&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FFFFFFFF&quot; Geometry=&quot;F1 M 731.354,562.147C 667.858,451.028 540.866,387.533 397.999,387.533C 255.134,387.533 128.142,451.028 64.6461,562.147C 128.142,673.266 255.134,736.762 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CCMVisible() As String
            Get
                Return ResourceManager.GetString("CCMVisible", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property IconHelp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("IconHelp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property IconScanner() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("IconScanner", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IconScanner1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IconScanner1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;ScannerConfigure&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 363.079,228.793C 356.728,228.793 353.552,233.555 351.965,238.319L 339.267,317.688C 313.868,324.037 290.057,335.149 267.833,347.848L 201.161,301.812C 196.4,298 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ScannerConfigure() As String
            Get
                Return ResourceManager.GetString("ScannerConfigure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;CCMSpreadsheet&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FF434242&quot; Geometry=&quot;F1 M 64.6459,308.163L 731.354,308.163L 731.354,800.257C 731.354,809.783 723.418,816.132 715.481,816.132L 80.5192,816.132C 72.5832,816.132 64.6459,8 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ScannerSpreadsheet() As String
            Get
                Return ResourceManager.GetString("ScannerSpreadsheet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TextureCardboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextureCardboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TextureVintage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextureVintage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
